Repository Makeshift/eve-goons-waitlist, pull requests merged in 2018-06, with the labels that each got.

#108 Waitlist logging, squads & general cleanup
  controllers/apiController.js
  controllers/fcToolsController.js
  controllers/fleetManagementController.js
  controllers/pagesController.js
  dbHandler.js
  fleets.js
  public/includes/css/custom.css
  routes.js
  users.js
  views/fcFleetManage.njk
  views/partials/nav.njk
  views/toolsFits.njk
  views/waitlist.njk
  views/waitlistLogs.njk
  wlog.js
Labels: Enhancement, UI

#109 Fixed CSS and DB Handler
  dbHandler.js
  public/includes/css/custom.css
  views/waitlistLogs.njk
Labels: Bug

#111 Waitlist Banners + No ESI Waitlist +failed invite feedback + user/users.js
  controllers/apiController.js
  controllers/commanderController.js
  controllers/fleetManagementController.js
  controllers/pagesController.js
  fleets.js
  globalWaitlist.js
  public/includes/css/custom.css
  routes.js
  user.js
  users.js
  views/fcFleetManage.njk
  views/partials/footer.njk
  views/partials/nav.njk
  views/waitlist.njk
  waitlistBanner.js
Labels: Enhancement, UI

#116 Fixed Cache
  .gitignore
  cache.js
  controllers/apiController.js
  user.js
Labels: Bug

#118 Fix for user registration + created models folder
  .gitignore
  controllers/adminBansController.js
  controllers/adminCommandersController.js
  controllers/apiController.js
  controllers/commanderController.js
  controllers/fcToolsController.js
  controllers/fleetManagementController.js
  controllers/pagesController.js
  controllers/pilotSettingsController.js
  controllers/statisticsController.js
  index.js
  models/bans.js
  models/fleets.js
  models/globalWaitlist.js
  models/user.js
  models/users.js
  models/waitlistBanner.js
  models/wlog.js
  routes.js
  ships.js
  views/partials/nav.njk
  views/squadStats.njk
Labels: Bug, Enhancement

#117 Scheduler + Tests using Jest. Also ES6 support
  .babelrc
  Dockerfile
  logger.js
  models/users.js
  models/wlog.js
  package-lock.json
  package.json
  scheduler/job.js
  scheduler/scheduler.js
  scheduler/task.js
  scheduler_index.js
  tests/job.test.js
  tests/scheduler.test.js
  tests/task.test.js
Labels: Enhancement

#122 Hot FIX
  models/users.js
Labels: Bug

#123 Side bar + Pilot Search and Bug fixes
  controllers/apiController.js
  models/user.js
  models/whitelist.js
  routes.js
  scheduler_index.js
  views/adminBan.njk
  views/adminFC.njk
  views/adminWhitelist.njk
  views/fcFleetList.njk
  views/fcFleetManage.njk
  views/partials/footer.njk
  views/partials/nav.njk
  views/pilotSettings.njk
  views/squadStats.njk
  views/toolsFits.njk
  views/toolsPilotSearch.njk
  views/toolsSkills.njk
  views/waitlist.njk
  views/waitlistLogs.njk
Labels: Bug, Enhancement
